#!/bin/bash

echo "🚀 Portal de Gestão - Deploy Manual"
echo ""
echo "================================================"
echo "OPÇÃO 1: Cloudflare (Recomendado)"
echo "================================================"
echo ""
echo "1. Vá para: https://dash.cloudflare.com"
echo "2. Crie uma nova aplicação Workers"
echo "3. Execute:"
echo ""
echo "   npx wrangler login"
echo "   npm run build"
echo "   npx wrangler deploy"
echo ""
echo "📍 URL: https://seu-projeto.workers.dev"
echo ""
echo "================================================"
echo "OPÇÃO 2: Vercel (Fácil)"
echo "================================================"
echo ""
echo "1. Vá para: https://vercel.com"
echo "2. Clique em 'Import Project'"
echo "3. Cole: https://github.com/McdImperial/Portal-imperial"
echo "4. Deploy automático"
echo ""
echo "📍 URL: https://portal-imperial.vercel.app"
echo ""
echo "================================================"
echo "OPÇÃO 3: Netlify (Muito Fácil)"
echo "================================================"
echo ""
echo "1. Vá para: https://netlify.com"
echo "2. Clique em 'Deploy from Git'"
echo "3. Selecione seu repositório"
echo "4. Deploy automático"
echo ""
echo "📍 URL: https://portal-imperial.netlify.app"
echo ""
