"use client";

import { type FormEvent, useState } from "react";

const managers = ["Ricardo Teixeira", "Susana Torres", "Sara Sousa", "Miguel Matela", "Soraia Martins", "André Martins", "Liliana Pacheco", "Diogo Cabral", "Sílvia Tavares", "Ana Sousa"];
const period = "2.º Quadrimestre 2026";
const sections = [
  { id:"building", title:"Building Blocks", subtitle:"Qualidades que promovem uma alta performance", weight:37, criteria:["Ganha a confiança dos outros ajustando o seu estilo de comunicação e influenciando de forma positiva, demonstrando assertividade para dizer sim ou não, quando necessário.","Vivencia os valores da empresa no desempenho da sua função, assegurando e promovendo os padrões e normas da McDonald’s.","Mantém o controlo emocional e a produtividade em ambientes de grande pressão, conseguindo manter uma atitude positiva.","Demonstra respeito e compreensão pelos outros, adaptando-se ao grupo e construindo espírito de equipa.","Durante a execução da sua função, dá orientações claras e demonstra padrões de comportamento adequados."] },
  { id:"execution", title:"Execução", subtitle:"Cumpre o desempenho da função", weight:25, criteria:["Responsabiliza-se a si e à sua equipa no cumprimento de procedimentos de forma rigorosa e com foco na obtenção de resultados alinhados com as métricas da McDonald’s.","Faz uma gestão eficaz durante o turno (pessoas, equipamentos, qualidade e serviço), reavaliando continuamente as prioridades e antecipando problemas.","Tem domínio sobre a sua função, atuando com autonomia e segurança no cumprimento das suas responsabilidades.","Faz uma gestão eficaz das suas responsabilidades extra turnos (tarefas secundárias), de forma a atingir os objetivos estabelecidos para o restaurante."] },
  { id:"strategy", title:"Orientação Estratégia", subtitle:"Desenvolve uma visão estratégica alinhada com os objetivos da empresa", weight:16, criteria:["Orienta a equipa e é um exemplo na priorização do cliente como o centro de tudo, antecipando necessidades e expectativas dos mesmos (internos e externos).","Demonstra comportamentos de um verdadeiro embaixador McDonald’s, elevando a imagem do restaurante e da marca.","Conhece, entende e contribui para o alcance dos objetivos gerais do restaurante."] },
  { id:"talent", title:"Talento", subtitle:"Inspirar e promover o talento", weight:22, criteria:["Identifica as suas áreas de oportunidades e da equipa e apoia o desenvolvimento.","Comunica de forma transparente e revela continuamente uma escuta ativa, promovendo o crescimento dos outros.","Reconhece o desempenho individual e de equipa.","Mantém-se constantemente atento na identificação de potencial na equipa."] },
];
function rating(score:number){if(score<=1.2)return"Insuficiente";if(score<=2.6)return"Suficiente";if(score<=3.2)return"Bom";if(score<=3.6)return"Bom +";return"Muito Bom";}

export default function SelfEvaluationPage(){
  const [managerName,setManagerName]=useState(""); const [scores,setScores]=useState<Record<string,number>>({}); const [strengths,setStrengths]=useState(""); const [improvements,setImprovements]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [success,setSuccess]=useState(false);
  const complete=sections.every((section)=>section.criteria.every((_,index)=>scores[`${section.id}-${index}`]));
  const unanswered=sections.reduce((total,section)=>total+section.criteria.filter((_,index)=>!scores[`${section.id}-${index}`]).length,0);
  const total=sections.reduce((sum,section)=>{const values=section.criteria.map((_,index)=>scores[`${section.id}-${index}`]||0);return sum+(values.reduce((a,b)=>a+b,0)/values.length)*section.weight/100;},0);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!complete||busy)return;setBusy(true);setMessage("");const response=await fetch("/api/management-performance/self",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({managerName,period,scores,quantitativeScore:total,qualitativeRating:rating(total),strengths,improvements})});const data=await response.json() as {message?:string;error?:string};setSuccess(response.ok);setMessage(response.ok?(data.message||"Autoavaliação enviada."):(data.error||"Não foi possível enviar."));if(response.ok){setScores({});setStrengths("");setImprovements("");setManagerName("");}setBusy(false);}
  return <main className="self-evaluation-shell"><section className="self-evaluation-card"><header className="self-evaluation-brand"><span>M</span><div><strong>McDonald&apos;s Imperial</strong><small>Equipa de Gestão</small></div></header><div className="self-evaluation-heading"><span className="eyebrow">Avaliação de desempenho</span><h1>Autoavaliação EG</h1><p>Classifique cada afirmação de 1 a 4, tendo em conta o seu desempenho no período indicado.</p></div><form onSubmit={submit} className="self-evaluation-form"><div className="self-evaluation-basics"><label>Gerente<select value={managerName} onChange={(event)=>setManagerName(event.target.value)} required><option value="">Selecionar nome</option>{managers.map((name)=><option key={name}>{name}</option>)}</select></label><label>Quadrimestre<select value={period} disabled><option>{period}</option></select></label></div>{sections.map((section)=><section className={`self-evaluation-section ${section.id}`} key={section.id}><header><div><h2>{section.title}</h2><p>{section.subtitle}</p></div><strong>{section.weight}%</strong></header>{section.criteria.map((criterion,index)=>{const key=`${section.id}-${index}`;return <fieldset key={key}><legend>{criterion}</legend><div>{[1,2,3,4].map((value)=><label key={value}><input type="radio" name={key} value={value} checked={scores[key]===value} onChange={()=>setScores((current)=>({...current,[key]:value}))} required/><span>{value}</span></label>)}</div></fieldset>;})}</section>)}<div className="self-evaluation-result"><div><small>Nota quantitativa</small><strong>{complete?total.toFixed(2).replace(".",","):"—"}</strong></div><div><small>Nota qualitativa</small><strong>{complete?rating(total):"Por calcular"}</strong></div></div><div className="self-evaluation-notes"><label>Pontos fortes<textarea rows={4} value={strengths} onChange={(event)=>setStrengths(event.target.value)} placeholder="Descreva os seus principais pontos fortes"/></label><label>Pontos a melhorar<textarea rows={4} value={improvements} onChange={(event)=>setImprovements(event.target.value)} placeholder="Indique as áreas que pretende desenvolver"/></label></div>{unanswered>0&&<p className="self-evaluation-incomplete">Faltam responder {unanswered} {unanswered===1?"questão":"questões"}. A autoavaliação só pode ser enviada quando estiver completa.</p>}{message&&<p className={`self-evaluation-message ${success?"success":""}`}>{message}</p>}<button type="submit" disabled={!managerName||!complete||busy}>{busy?"A enviar…":"Enviar autoavaliação"}</button></form></section></main>;
}
